/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Quests', [
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/24655e8e-038c-44d7-b0ba-ce4f1e518be4.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/5b9d968f-eb2d-45f9-bcfe-96a05fcbbfd3.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/986816ac-2ce0-45b1-99b7-6e9beedda151.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/aa19b039-7d46-4590-b31d-8261174f90a3.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/c6243619-585f-4838-a5ee-752ff3060730.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/58a9e401-8019-4997-a05d-7bb18e95dac2.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/8033e6e5-40c5-46ee-8699-7644ac43daa0.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/5be62420-fa2c-4050-85c7-5b376cb617f4.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/eb414974-b23e-4edf-be95-a8400a54b9ae.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn2.myquiz.ru/userphotos/800/8988243b-8973-4314-8a24-cd63115b5506.jpg',
        title: 'Назовите мультфильм',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://cdn.shazoo.ru/580407_jVFwhcs1te_34.jpg',
        title: 'Когда Лео поднял этот знаменитый тост?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://risovach.ru/upload/2014/07/mem/nelzya-prosto-tak-vzyat-i-boromir-mem_54809432_orig_.jpg',
        title: 'Что показывает Боромир ?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://snob.ru/indoc/og/80/37/8037e87b151bbdff032207cdcafcbef7abbf38fb3749868ea10507a89ee726f7.jpeg',
        title: 'На что, по его словам, аллергия у героя Уилла Смита, пьющего чай из крохотной чашки?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://in-w.ru/wp-content/uploads/2020/05/Race-to-Witch-Mountain-mem.jpg',
        title: 'Из какого фильма данный мем?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://korzik.net/uploads/posts/2022-07/23003204302.jpg',
        title: 'В какой ситуации Фрай из "Футурамы" кричит "Заткнись и возьми мои деньги"?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://www.meme-arsenal.com/memes/8eedd482b6a7a807abe1cb7ea876f074.jpg',
        title: 'Куда отправились судебные приставы - герои Руффало и Ди Каприо?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://risovach.ru/upload/2014/03/mem/nu-davay-taya-rasskazhi-kak-ty-men_46435754_big_.jpeg',
        title: 'Кто перед вами?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://avatars.dzeninfra.ru/get-zen_doc/2749135/pub_5ebb8cb1e4773935a4023011_5ebb8e1c3d23d611ec016ef0/scale_1200',
        title: 'Название сериала',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://tvrain.tv/library/1200x630/477d93/media/photo/original/20150504/46401aa1a82db5f76c02936fab9643bc.jpg',
        title: 'Откуда мем?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: 'https://avatars.dzeninfra.ru/get-zen_doc/1852570/pub_5da6d6d043863f00b187ab16_5da6d7c35ba2b500aef5a6d3/scale_1200',
        title: 'Что произойдет с банкой в этой сцене "Настоящего детектива"?',
        themeId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Quests', null, {});
  },
};
